// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nextFingers
Rcpp::LogicalVector nextFingers(double markedN, Rcpp::NumericMatrix fingers0, double Rclusters);
RcppExport SEXP _mat3c_nextFingers(SEXP markedNSEXP, SEXP fingers0SEXP, SEXP RclustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type markedN(markedNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type fingers0(fingers0SEXP);
    Rcpp::traits::input_parameter< double >::type Rclusters(RclustersSEXP);
    rcpp_result_gen = Rcpp::wrap(nextFingers(markedN, fingers0, Rclusters));
    return rcpp_result_gen;
END_RCPP
}
// shadowcpp
double shadowcpp(const int N, const arma::mat& X, const int Cc, const arma::vec& x, const arma::vec& y, const arma::vec& t, const double sigma, const double r);
RcppExport SEXP _mat3c_shadowcpp(SEXP NSEXP, SEXP XSEXP, SEXP CcSEXP, SEXP xSEXP, SEXP ySEXP, SEXP tSEXP, SEXP sigmaSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type Cc(CcSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(shadowcpp(N, X, Cc, x, y, t, sigma, r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mat3c_nextFingers", (DL_FUNC) &_mat3c_nextFingers, 3},
    {"_mat3c_shadowcpp", (DL_FUNC) &_mat3c_shadowcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_mat3c(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
