# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nextFingers <- function(markedN, fingers0, Rclusters) {
    .Call('_mat3c_nextFingers', PACKAGE = 'mat3c', markedN, fingers0, Rclusters)
}

shadowcpp <- function(N, X, Cc, x, y, t, sigma, r) {
    .Call('_mat3c_shadowcpp', PACKAGE = 'mat3c', N, X, Cc, x, y, t, sigma, r)
}

